post_install() {
 chown nobody /var/lib/mympd

 echo "Trying to link musicdir to library"
  if [ -f /etc/mpd.conf ]
  then
    LIBRARY=$(grep music /etc/mpd.conf | awk {'print $2'})
    [ "$LIBRARY" != "" ] && [ ! -e /usr/share/mympd/htdocs/library ] && ln -s $LIBRARY /usr/share/mympd/htdocs/library
  else
    echo "/etc/mpd.conf not found, you must link your musicdir manually to /usr/share/mympd/htdocs/library"
 fi
}
